language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.3
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

services:
  - docker

before_install:
  - docker pull rigetti/qvm
  - docker pull rigetti/quilc
  - docker run -d -it -p 5555:5555 rigetti/quilc -S
  - docker run -d -it -p 5000:5000 rigetti/qvm -S

install:
  - pip3 install --upgrade pip
  - pip3 install -r deploy/requirements.txt
  - pip3 install -e .
  - pip3 install pytest pytest-cov sphinx sphinx_rtd_theme

script:
- cd docs && make html && cd ..
- pytest -v --cov=qucochemistry
